name: Example - Run Javascript Advanced

on:
  workflow_dispatch:
  push:

jobs:
  run-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Show function of github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(this)

      - name: Return back value
        uses: actions/github-script@v7
        id: my-script
        with:
          result-encoding: string
          retries: 3
          script: |
            return 'Hello, World!'
      - name: Get result
        run: echo "${{steps.my-script.outputs.result}}"