name: Example - Run Javascript Advanced

on:
  push:
  workflow_dispatch:

jobs:
  run-javascript:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@main
          
      # input and output
      - name: set input
        id: set-input
        run: |
          echo 'hello=Hello' > $GITHUB_ENV
          echo 'world=World' > $GITHUB_OUTPUT
      - name: get and set env
        id: get-and-set-env
        uses: actions/github-script@main
        env:
          COMMA: ', '
        with:
          script: |
            const hello = process.env.hello
            const world = "${{ steps.set-input.outputs.world }}"
            const comma = process.env.COMMA
            console.log(hello, comma, world, '!')
            core.exportVariable('WORLD', hello + comma + world + '!')
            return { greeting: hello + comma + 'world!', array: [1, 2, 3]}
          result-encoding: json
      - name: print output
        run: |
          echo $WORLD
          echo "${{ steps.get-and-set-env.outputs.result.greeting }}"
          echo "${{ steps.get-and-set-env.outputs.result }}"
        
      # run script from file
      - name: run outer script
        uses: actions/github-script@main
        with:
          script: |
            console.log('--- run script from file ---');
            const fs = require('fs')
            const script = fs.readFileSync('.github/workflows/example/hello-world.js')
            const text = "Eval script"
            Function('text', script)(text);
            console.log('\n--- run sync script from file ---\n');
            const script_sync = require('.github/workflows/example/hello-world-sync.js')
            script_sync(github, context, core, "Synchronous function")
            console.log('\n--- run async script from file ---\n');
            const script_async = require('.github/workflows/example/hello-world-async.js')
            await script_async(github, context, core, "Asynchronous function")
      
      # save context to file
      - name: Save functions of github-script to file
        uses: actions/github-script@main
        with:
          script: |
            const fs = require('fs')
            const util = require('util');
            fs.writeFileSync('github-script-context.txt', 'this = ' + util.inspect(this) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'github = ' + util.inspect(github) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'context = ' + util.inspect(context) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'core = ' + util.inspect(core) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'glob = ' + util.inspect(glob) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'io = ' + util.inspect(io) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'exec = ' + util.inspect(exec) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'require = ' + util.inspect(require) + '\n\n')
            process.env['INPUT_GITHUB-TOKEN'] = '***'
            process.env['ACTIONS_RUNTIME_TOKEN'] = '***'
            fs.appendFileSync('github-script-context.txt', 'process = ' + util.inspect(process) + '\n\n')
            fs.appendFileSync('github-script-context.txt', 'global = ' + util.inspect(global) + '\n\n')
      - name: upload-artifact
        uses: actions/upload-artifact@main
        with:
          name: github-script-context
          path: github-script-context.txt

      # use REST Api to set latest release to hello world + runNumber
      - name: Use REST Api to set latest release to hello world
        uses: actions/github-script@main
        with:
          script: |
            const response = await github.request('GET /repos/{owner}/{repo}/releases/latest', {
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(response.data)
            const release = response.data
            const result = await github.request('PATCH /repos/{owner}/{repo}/releases/{release_id}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              tag_name: 'v0.0.0.1',
              name: 'Hello World Release',
              body: 'Hello World ' + context.runNumber,
            })
            console.log(result.data)
            core.exportVariable('RELEASE', release.id)
      - name: Use REST Api to upload assets to release
        uses: actions/github-script@main
        with:
          script: |
            // listReleaseAssets
            const ids = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.RELEASE,
            });
            console.log(ids)
            // deleteReleaseAsset
            for (const id of ids) {
              github.rest.repos.deleteReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                asset_id: id.id,
              });
            }
            // uploadReleaseAsset
            const fs = require('fs')
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.RELEASE,
              name: `github-script-context-${context.runNumber}.txt`,
              data: fs.readFileSync('github-script-context.txt'),
            })
            
