name: Example - Run Javascript Advanced

on:
  workflow_dispatch:

jobs:
  run-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: my-script
        with:
          result-encoding: string
          retries: 3
          script: |
            console.log(github)
            console.log(context)
            console.log(core)
            console.log(glob)
            console.log(io)
            console.log(exec)
            console.log(require)
      - name: Get result
        run: echo "${{steps.my-script.outputs.result}}"